import {
  siAndroid,
  siBambulab,
  siC,
  siCaddy,
  siCloudflare,
  siCplusplus,
  siDocker,
  siElectron,
  siFedora,
  siFirebase,
  siGit,
  siGithub,
  siGooglechrome,
  siJavascript,
  siKotlin,
  siNextdotjs,
  siNodedotjs,
  siOpenscad,
  siAutodesk,
  siPython,
  siRazorpay,
  siReact,
  siSqlite,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siVercel,
  siVite,
  type SimpleIcon,
} from "simple-icons";

export type Skill = { label: string; icon: SimpleIcon };

export const skills: Skill[] = [
  { label: "JavaScript", icon: siJavascript },
  { label: "TypeScript", icon: siTypescript },
  { label: "Kotlin", icon: siKotlin },
  { label: "Python", icon: siPython },
  { label: "C++", icon: siCplusplus },
  { label: "C", icon: siC },
  { label: "React", icon: siReact },
  { label: "Next.js", icon: siNextdotjs },
  { label: "Vite", icon: siVite },
  { label: "Tailwind", icon: siTailwindcss },
  { label: "Node.js", icon: siNodedotjs },
  { label: "SQLite", icon: siSqlite },
  { label: "Supabase", icon: siSupabase },
  { label: "Firebase", icon: siFirebase },
  { label: "Razorpay", icon: siRazorpay },
  { label: "Android", icon: siAndroid },
  { label: "Electron", icon: siElectron },
  { label: "Chrome extensions", icon: siGooglechrome },
  { label: "Fedora", icon: siFedora },
  { label: "Docker", icon: siDocker },
  { label: "Caddy", icon: siCaddy },
  { label: "Cloudflare", icon: siCloudflare },
  { label: "Vercel", icon: siVercel },
  { label: "Git", icon: siGit },
  { label: "GitHub", icon: siGithub },
  { label: "Fusion 360", icon: siAutodesk },
  { label: "OpenSCAD", icon: siOpenscad },
  { label: "Bambu Studio", icon: siBambulab },
];
